<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-04-25 08:14
=======
# Generated by Django 5.0.3 on 2024-04-21 15:13
>>>>>>> parent of 4bbdbee (deleted html not in template)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pic')),
=======
                ('image', models.ImageField(upload_to='profile_pic')),
>>>>>>> parent of 4bbdbee (deleted html not in template)
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
